import HautevilleHouse.MolecularBiologyReverseTranscriptionFoundationCanonicalLaneLean.ReverseTranscriptionEnzymeKinetics
import HautevilleHouse.MolecularBiologyReverseTranscriptionFoundationCanonicalLaneLean.ReverseTranscriptionInitiationElongationTermination
import HautevilleHouse.MolecularBiologyReverseTranscriptionFoundationCanonicalLaneLean.ReverseTranscriptionMutationAndRecombination
import HautevilleHouse.MolecularBiologyReverseTranscriptionFoundationCanonicalLaneLean.ReverseTranscriptionInhibitorTherapy
import HautevilleHouse.MolecularBiologyReverseTranscriptionFoundationCanonicalLaneLean.ReverseTranscriptionFoundationAdmissibleClass

-- This module collects all imports for the RT foundation package.

namespace HautevilleHouse
namespace MolecularBiologyReverseTranscriptionFoundationCanonicalLaneLean

-- Marker theorem: the package is unified under the constrained RT closure.
theorem rt_foundation_present (A : AdmissibleClass) : ConstrainedRTClosure A :=
  constrained_rt_endgame A

end MolecularBiologyReverseTranscriptionFoundationCanonicalLaneLean
end HautevilleHouse